### ISSUE TITLE
Nice project, interesting ideas like the typing of requests/responses. Roadmap?

### ISSUE THREAD

**Issue by tzkmx** [plugcore/framework#14]
I started an empty project (FWIW, with any previous git clone, just npx init) and check the example.

However is not that clear to me how to proceed from there, in issues like validation, or middlewares, etc.

Also, I'd like to know if there is a way to export the project and host it in an environment capable to run any node.js script without a complete stack to maintain, i.e. serverless (Azure/Cloud Functions), or it is required to be run through the plug binary?

In that case, a complete environment is required? Azure and Lambdas are capable of running custom stacks, but seems a lot of work to do.

How about documentation? I'd like to know where are you going, so far what I've seen is very interesting.

Happy to read your reply 🇲🇽

**Comment by SergioLarios** [comment]
Hi! First of all, we still have to create a ROADMAP but we are already working on features such as a better OAS Documentation generator, save and create statistics with the logs, and email alerts when some service is down.

We have added the ability to start the project without the need of a CLI in the version `1.2.7`, please read https://github.com/plugcore/framework/wiki/Project-initialization#manual-start for forther information.

We can continue talking over discrod about this, but i'm closing this issue for housekeeping purposes.
